In [1]:
from pyscan.ephys import ephys

path = '/home/isabella/Documents/isabella/jake/recording_data/r1503/2024-03-20'
sheet_url = 'https://docs.google.com/spreadsheets/d/1cZxgOw7worcVZq8wIPslmU2jD__xm1MXnNgbs1-9ros/edit#gid=0'

obj = ephys('NP2_openephys', path, sheet_url)
obj.load_ttl()
obj.sync_data

No trial list specified, loading TTL data for all trials
Loading TTL data for 240320_r1503_sleep-ml_1
Loading TTL data for 240320_r1503_open-field-ml_2
Loading TTL data for 240320_r1503_open-field-sl_3


[array([], dtype=float64),
 array([  9.951     ,  13.6947    ,  13.7347    , ..., 745.6128    ,
        745.65283333, 745.69283333]),
 array([  8.28493333,  12.2675    ,  12.30753333, ..., 284.6963    ,
        284.73633333, 284.7763    ])]

In [14]:
import numpy as np
obj.sync_data[2]

array([  3.3688    ,   3.36883333,   3.36886667, ..., 288.00403333,
       288.00406667, 288.0041    ])

In [19]:
ttl_data.channel_ids

array(['Messages', 'Neuropixels PXI Sync'], dtype='<U64')